#INSERT DATA FROM FILE. C drive is not stable 
#MYSQL DEFAULT PATH IS DEPEND ON OS, VERSION OF SQL. MINE IS /DATA/MARIADB_HDD/MYSQL

LOAD DATA (LOCAL) INFILE 'D:\data/fns_u_invest_20170530.DAT' INTO TABLE FMKSP200_DATA
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';
